
package com.bmtc.system.utils.BMTC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BMTCSoap", targetNamespace = "BMTC")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BMTCSoap {


    /**
     * 
     * @return
     *     returns com.bmtc.system.utils.BMTC.ArrayOfUserInfo
     */
    @WebMethod(operationName = "GetUserLists", action = "BMTC/GetUserLists")
    @WebResult(name = "GetUserListsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetUserLists", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetUserLists")
    @ResponseWrapper(localName = "GetUserListsResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetUserListsResponse")
    public ArrayOfUserInfo getUserLists();

    /**
     * 
     * @return
     *     returns com.bmtc.system.utils.BMTC.ArrayOfString
     */
    @WebMethod(operationName = "GetAllProducts", action = "BMTC/GetAllProducts")
    @WebResult(name = "GetAllProductsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetAllProducts", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetAllProducts")
    @ResponseWrapper(localName = "GetAllProductsResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetAllProductsResponse")
    public ArrayOfString getAllProducts();

    /**
     * 
     * @return
     *     returns com.bmtc.system.utils.BMTC.ArrayOfString
     */
    @WebMethod(operationName = "GetBatchList", action = "BMTC/GetBatchList")
    @WebResult(name = "GetBatchListResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetBatchList", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetBatchList")
    @ResponseWrapper(localName = "GetBatchListResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetBatchListResponse")
    public ArrayOfString getBatchList();

    /**
     * 
     * @return
     *     returns com.bmtc.system.utils.BMTC.ArrayOfRound
     */
    @WebMethod(operationName = "GetRoundList", action = "BMTC/GetRoundList")
    @WebResult(name = "GetRoundListResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetRoundList", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetRoundList")
    @ResponseWrapper(localName = "GetRoundListResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetRoundListResponse")
    public ArrayOfRound getRoundList();

    /**
     * 
     * @param password
     * @param produceID
     * @param loginName
     * @param departmentID
     * @param teamID
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateATPUser", action = "BMTC/CreateATPUser")
    @WebResult(name = "CreateATPUserResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "CreateATPUser", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.CreateATPUser")
    @ResponseWrapper(localName = "CreateATPUserResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.CreateATPUserResponse")
    public String createATPUser(
        @WebParam(name = "userName", targetNamespace = "BMTC")
        String userName,
        @WebParam(name = "loginName", targetNamespace = "BMTC")
        String loginName,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password,
        @WebParam(name = "departmentID", targetNamespace = "BMTC")
        int departmentID,
        @WebParam(name = "teamID", targetNamespace = "BMTC")
        int teamID,
        @WebParam(name = "produceID", targetNamespace = "BMTC")
        ArrayOfInt produceID);

    /**
     * 
     * @param userID
     * @return
     *     returns com.bmtc.system.utils.BMTC.ArrayOfOrganization
     */
    @WebMethod(operationName = "GetUserProducts", action = "BMTC/GetUserProducts")
    @WebResult(name = "GetUserProductsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetUserProducts", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetUserProducts")
    @ResponseWrapper(localName = "GetUserProductsResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.GetUserProductsResponse")
    public ArrayOfOrganization getUserProducts(
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID);

    /**
     * 
     * @param scriptSVNPath
     * @param password
     * @param productID
     * @param caseNum
     * @param caseName
     * @param batchID
     * @param repository
     * @param userID
     * @param productName
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveATPCases", action = "BMTC/SaveATPCases")
    @WebResult(name = "SaveATPCasesResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "SaveATPCases", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.SaveATPCases")
    @ResponseWrapper(localName = "SaveATPCasesResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.SaveATPCasesResponse")
    public String saveATPCases(
        @WebParam(name = "batchID", targetNamespace = "BMTC")
        int batchID,
        @WebParam(name = "productID", targetNamespace = "BMTC")
        int productID,
        @WebParam(name = "caseNum", targetNamespace = "BMTC")
        String caseNum,
        @WebParam(name = "caseName", targetNamespace = "BMTC")
        String caseName,
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID,
        @WebParam(name = "scriptSVNPath", targetNamespace = "BMTC")
        String scriptSVNPath,
        @WebParam(name = "productName", targetNamespace = "BMTC")
        String productName,
        @WebParam(name = "repository", targetNamespace = "BMTC")
        String repository,
        @WebParam(name = "username", targetNamespace = "BMTC")
        String username,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password);

    /**
     * 
     * @param deviceType
     * @param productID
     * @param caseNum
     * @param batchID
     * @param repository
     * @param userID
     * @param productName
     * @param scriptSVNPath
     * @param password
     * @param caseName
     * @param udid
     * @param testClientIP
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UploadATPTasks", action = "BMTC/UploadATPTasks")
    @WebResult(name = "UploadATPTasksResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "UploadATPTasks", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.UploadATPTasks")
    @ResponseWrapper(localName = "UploadATPTasksResponse", targetNamespace = "BMTC", className = "com.bmtc.system.utils.BMTC.UploadATPTasksResponse")
    public boolean uploadATPTasks(
        @WebParam(name = "batchID", targetNamespace = "BMTC")
        int batchID,
        @WebParam(name = "productID", targetNamespace = "BMTC")
        int productID,
        @WebParam(name = "caseNum", targetNamespace = "BMTC")
        String caseNum,
        @WebParam(name = "caseName", targetNamespace = "BMTC")
        String caseName,
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID,
        @WebParam(name = "scriptSVNPath", targetNamespace = "BMTC")
        String scriptSVNPath,
        @WebParam(name = "TestClientIP", targetNamespace = "BMTC")
        String testClientIP,
        @WebParam(name = "DeviceType", targetNamespace = "BMTC")
        String deviceType,
        @WebParam(name = "UDID", targetNamespace = "BMTC")
        String udid,
        @WebParam(name = "productName", targetNamespace = "BMTC")
        String productName,
        @WebParam(name = "repository", targetNamespace = "BMTC")
        String repository,
        @WebParam(name = "username", targetNamespace = "BMTC")
        String username,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password);

}
