
package com.bmtc.system.utils.BMTC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BMTC", targetNamespace = "BMTC", wsdlLocation = "file:/C:/Users/Administrator/Desktop/BMTC.asmx.xml")
public class BMTC
    extends Service
{

    private final static URL BMTC_WSDL_LOCATION;
    private final static WebServiceException BMTC_EXCEPTION;
    private final static QName BMTC_QNAME = new QName("BMTC", "BMTC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/BMTC.asmx.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BMTC_WSDL_LOCATION = url;
        BMTC_EXCEPTION = e;
    }

    public BMTC() {
        super(__getWsdlLocation(), BMTC_QNAME);
    }

    public BMTC(WebServiceFeature... features) {
        super(__getWsdlLocation(), BMTC_QNAME, features);
    }

    public BMTC(URL wsdlLocation) {
        super(wsdlLocation, BMTC_QNAME);
    }

    public BMTC(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BMTC_QNAME, features);
    }

    public BMTC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BMTC(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BMTCSoap
     */
    @WebEndpoint(name = "BMTCSoap")
    public BMTCSoap getBMTCSoap() {
        return super.getPort(new QName("BMTC", "BMTCSoap"), BMTCSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BMTCSoap
     */
    @WebEndpoint(name = "BMTCSoap")
    public BMTCSoap getBMTCSoap(WebServiceFeature... features) {
        return super.getPort(new QName("BMTC", "BMTCSoap"), BMTCSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BMTC_EXCEPTION!= null) {
            throw BMTC_EXCEPTION;
        }
        return BMTC_WSDL_LOCATION;
    }

}
